server:
  port: 8002
spring:
  application:
    name: cloud-payment-service
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 30MB
  datasource:
    url: jdbc:mysql://182.254.146.46:3306/cloud?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: Cwh032308....
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  devtools:
    livereload:
      port: 35702

eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
#      defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: payment8002
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 1
    lease-renewal-interval-in-seconds: 2

mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.raptor.common.entity.domain
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true
    use-generated-keys: true
    default-executor-type: reuse
#    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
